buildscript {
    ext.kotlin_version = '1.8.22'
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath 'com.chaquo.python:gradle:15.0.1'
    }
}

ext {
    flutter = [
        compileSdkVersion: 34,
        targetSdkVersion: 34,
        minSdkVersion: 24
    ]
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

subprojects { project ->
    if (project.name != 'app') {
        project.afterEvaluate {
            if (project.hasProperty('android')) {
                if (project.android.namespace == null) {
                    project.android.namespace = "com.ibnutify." + project.name.replace("-", "_").replace(":", "_")
                }
                project.android {
                    compileOptions {
                        sourceCompatibility JavaVersion.VERSION_17
                        targetCompatibility JavaVersion.VERSION_17
                    }
                }
            }
            project.tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
                kotlinOptions {
                    jvmTarget = "17"
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
